#!/usr/bin/env bash

if [ "$WERCKER_GENERATE_VERSION_IGNORE_BRANCHES" = "false" ]
then
	GENERATED_BUILD_NR=$($WERCKER_STEP_ROOT/fetch.py -U $WERCKER_GENERATE_VERSION_BASE_URL -u $WERCKER_GENERATE_VERSION_USERNAME -k $WERCKER_GENERATE_VERSION_API_KEY -a $WERCKER_GENERATE_VERSION_FOR_APP -b $WERCKER_GIT_BRANCH -c $WERCKER_GIT_COMMIT)
fi

if [[ "$GENERATED_BUILD_NR" = "" ]]; then
	echo ""
	echo "Failed to get build number" 1>&2

	return 1 2>/dev/null || exit 1
else
	echo "\$GENERATED_BUILD_NR: $GENERATED_BUILD_NR"
fi